name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Publish
      run: dotnet publish -r linux-x64 -c Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GlyfiBot_linux-x64
        path: "GlyfiBot/bin/Release/net9.0/linux-x64/publish/"
